version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "dwillcocks"

  - package-ecosystem: "docker"
    directory: "/blackbox_exporter"
    schedule:
      interval: "daily"
    assignees:
      - "dwillcocks"

  - package-ecosystem: "docker"
    directory: "/grafana"
    schedule:
      interval: "daily"
    assignees:
      - "dwillcocks"

  - package-ecosystem: "docker"
    directory: "/prometheus"
    schedule:
      interval: "daily"
    assignees:
      - "dwillcocks"
